package com.iktpreobuka.egradebook.services.utils.enums;

public enum ESubjectName {
	GENERAL_EDUCATION, SERBIAN_LANGUAGE_AND_LITERATURE, MATHEMATICS, ENGLISH_LANGUAGE, FINE_ART, MUSIC,
	PHYSICAL_EDUCATION, RELIGIOUS_EDUCATION, CIVICS, THE_WORLD_AROUND_US, FOREIGN_LANGUAGE_I, FOREIGN_LANGUAGE_II,
	HISTORY, BIOLOGY, GEOGRAPHY, PHYSICS, CHEMISTRY, INFORMATION_TECHNOLOGY, TECHNICAL_SCIENCES
}
