package com.iktpreobuka.egradebook.enums;

public enum ESubject {
	GENERAL_EDUCATION, SERBIAN_LANGUAGE, MATHEMATICS, ENGLISH_LANGUAGE, ART, MUSIC, PHYSICAL_EDUCATION,
	FOREIGN_LANGUAGE_I, FOREIGN_LANGUAGE_II, HISTORY, BIOLOGY, GEOGRAPHY, PHYSICS, CHEMISTRY, INFORMATION_TECHNOLOGY
}
